image: node:16.19.0

pipelines:
  default:
    - step:
        script:
          - npm ci
          - npx gulp build
        artifacts:
          - deploy/**
    - step:
        script:
          - pipe: atlassian/aws-s3-deploy:1.4.0
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: 'us-east-1'
              S3_BUCKET: 'staging.carnegiehighered.com/loyola'
              LOCAL_PATH: 'deploy'
              DELETE_FLAG: 'true'
